from pathlib import Path


def edit(path, replacements):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    for old, new in replacements:
        if old not in text:
            raise SystemExit(f'target not found in {path}: {old[:100]!r}')
        text = text.replace(old, new, 1)
    p.write_text(text, encoding='utf-8')


edit('core/src/main/java/com/codex/fx991/core/cw/CnCwScreen.java', [
    ('    CATALOG_CONVERSION_ITEMS,\n    CATALOG_PROBABILITY,',
     '    CATALOG_CONVERSION_ITEMS,\n    CATALOG_PROBABILITY,\n    CATALOG_COMPLEX,'),
    ('                    CATALOG_CONVERSION_ITEMS,\n                    CATALOG_PROBABILITY, TOOLS, CATALOG_RELATIONS,',
     '                    CATALOG_CONVERSION_ITEMS,\n                    CATALOG_PROBABILITY, CATALOG_COMPLEX, TOOLS, CATALOG_RELATIONS,'),
])

edit('core/src/main/java/com/codex/fx991/core/cw/CnCwWorkflowSpec.java', [
    ('        if (commandId.equals("matrix-det") || commandId.equals("matrix-inverse")\n                || commandId.equals("matrix-transpose")) {',
     '        if (commandId.equals("matrix-det") || commandId.equals("matrix-inverse")\n                || commandId.equals("matrix-transpose") || commandId.equals("matrix-square")\n                || commandId.equals("matrix-cube") || commandId.equals("matrix-abs")) {'),
    ('        if (commandId.equals("matrix-add") || commandId.equals("matrix-subtract")\n                || commandId.equals("matrix-multiply")) {',
     '        if (commandId.equals("matrix-identity")) {\n            return spec(ApplicationMode.MATRIX, commandId, "单位矩阵",\n                    InputLayout.FIXED_FIELDS,\n                    fields(field("dimension", "维数", FieldKind.EXPRESSION)),\n                    1, 1, 1, 1);\n        }\n        if (commandId.equals("matrix-add") || commandId.equals("matrix-subtract")\n                || commandId.equals("matrix-multiply")) {'),
    ('            case "matrix-transpose" -> "矩阵转置";\n            case "matrix-add" -> "矩阵加法";',
     '            case "matrix-transpose" -> "矩阵转置";\n            case "matrix-square" -> "矩阵平方";\n            case "matrix-cube" -> "矩阵立方";\n            case "matrix-identity" -> "单位矩阵";\n            case "matrix-abs" -> "元素绝对值";\n            case "matrix-add" -> "矩阵加法";'),
    ('        return choiceField(id, label,\n                choice("A", label.startsWith("左") || label.startsWith("右") ? "A" : "A"),\n                choice("B", "B"), choice("C", "C"), choice("D", "D"));',
     '        return choiceField(id, label,\n                choice("A", "A"), choice("B", "B"), choice("C", "C"), choice("D", "D"),\n                choice("Ans", "Ans"));'),
])

edit('core/src/main/java/com/codex/fx991/core/cw/CnCwLinearAlgebraMemory.java', [
    ('    private final Map<String, MatrixValue> matrices = new HashMap<>();\n    private final Map<String, VectorValue> vectors = new HashMap<>();',
     '    private final Map<String, MatrixValue> matrices = new HashMap<>();\n    private final Map<String, VectorValue> vectors = new HashMap<>();\n    private MatrixValue matrixAns;\n    private VectorValue vectorAns;'),
    ('        vectors.clear();\n        vectors.putAll(source.vectors);',
     '        vectors.clear();\n        vectors.putAll(source.vectors);\n        matrixAns = source.matrixAns;\n        vectorAns = source.vectorAns;'),
    ('        matrices.clear();\n        vectors.clear();\n    }',
     '        matrices.clear();\n        vectors.clear();\n        clearAnswers();\n    }\n\n    public void clearAnswers() {\n        matrixAns = null;\n        vectorAns = null;\n    }\n\n    public CnCwModeEngine.ModeResult answer(ApplicationMode mode) {\n        if (mode == ApplicationMode.MATRIX) {\n            if (matrixAns == null) throw new IllegalArgumentException("MatAns 未定义");\n            return matrixResult("MatAns", matrixAns);\n        }\n        if (mode == ApplicationMode.VECTOR) {\n            if (vectorAns == null) throw new IllegalArgumentException("VctAns 未定义");\n            return vectorResult("VctAns", vectorAns);\n        }\n        throw new IllegalArgumentException("No linear algebra answer for " + mode);\n    }'),
    ('            case "matrix-inverse" -> matrixResult(\n                    "Mat" + input.cell(0, 0) + "⁻¹", requireMatrix(input.cell(0, 0)).inverse());\n            case "matrix-transpose" -> matrixResult(\n                    "Trn(Mat" + input.cell(0, 0) + ")", requireMatrix(input.cell(0, 0)).transpose());\n            case "matrix-add" -> matrixResult(matrixBinaryTitle(input, "+"),\n                    requireMatrix(input.cell(0, 0)).add(requireMatrix(input.cell(0, 1))));\n            case "matrix-subtract" -> matrixResult(matrixBinaryTitle(input, "−"),\n                    requireMatrix(input.cell(0, 0)).subtract(requireMatrix(input.cell(0, 1))));\n            case "matrix-multiply" -> matrixResult(matrixBinaryTitle(input, "×"),\n                    requireMatrix(input.cell(0, 0)).multiply(requireMatrix(input.cell(0, 1))));',
     '            case "matrix-inverse" -> rememberMatrixResult(\n                    "Mat" + input.cell(0, 0) + "⁻¹", requireMatrix(input.cell(0, 0)).inverse());\n            case "matrix-transpose" -> rememberMatrixResult(\n                    "Trn(Mat" + input.cell(0, 0) + ")", requireMatrix(input.cell(0, 0)).transpose());\n            case "matrix-square" -> {\n                MatrixValue value = requireMatrix(input.cell(0, 0));\n                yield rememberMatrixResult("Mat" + input.cell(0, 0) + "²", value.multiply(value));\n            }\n            case "matrix-cube" -> {\n                MatrixValue value = requireMatrix(input.cell(0, 0));\n                yield rememberMatrixResult("Mat" + input.cell(0, 0) + "³",\n                        value.multiply(value).multiply(value));\n            }\n            case "matrix-identity" -> {\n                double raw = ScalarExpressionEngine.evaluate(input.cell(0, 0), context);\n                if (raw != Math.rint(raw) || raw < 1 || raw > 4) {\n                    throw new IllegalArgumentException("Identity size must be 1..4");\n                }\n                yield rememberMatrixResult("Identity(" + (int) raw + ")",\n                        MatrixValue.identity((int) raw));\n            }\n            case "matrix-abs" -> rememberMatrixResult(\n                    "Abs(Mat" + input.cell(0, 0) + ")", requireMatrix(input.cell(0, 0)).elementAbs());\n            case "matrix-add" -> rememberMatrixResult(matrixBinaryTitle(input, "+"),\n                    requireMatrix(input.cell(0, 0)).add(requireMatrix(input.cell(0, 1))));\n            case "matrix-subtract" -> rememberMatrixResult(matrixBinaryTitle(input, "−"),\n                    requireMatrix(input.cell(0, 0)).subtract(requireMatrix(input.cell(0, 1))));\n            case "matrix-multiply" -> rememberMatrixResult(matrixBinaryTitle(input, "×"),\n                    requireMatrix(input.cell(0, 0)).multiply(requireMatrix(input.cell(0, 1))));'),
    ('            case "vector-unit" -> vectorResult("Unit(Vct" + leftSlot + ")", left.unit());\n            case "vector-add" -> vectorResult(vectorBinaryTitle(input, "+"),\n                    left.add(requireVector(input.cell(0, 1))));\n            case "vector-subtract" -> vectorResult(vectorBinaryTitle(input, "−"),\n                    left.subtract(requireVector(input.cell(0, 1))));',
     '            case "vector-unit" -> rememberVectorResult("Unit(Vct" + leftSlot + ")", left.unit());\n            case "vector-add" -> rememberVectorResult(vectorBinaryTitle(input, "+"),\n                    left.add(requireVector(input.cell(0, 1))));\n            case "vector-subtract" -> rememberVectorResult(vectorBinaryTitle(input, "−"),\n                    left.subtract(requireVector(input.cell(0, 1))));'),
    ('            case "vector-cross" -> vectorResult(vectorBinaryTitle(input, "×"),\n                    left.cross(requireVector(input.cell(0, 1))));',
     '            case "vector-cross" -> rememberVectorResult(vectorBinaryTitle(input, "×"),\n                    left.cross(requireVector(input.cell(0, 1))));'),
    ('    private MatrixValue requireMatrix(String slot) {\n        MatrixValue value = matrices.get(slot);\n        if (value == null) throw new IllegalArgumentException("Mat" + slot + " 未定义");\n        return value;\n    }\n\n    private VectorValue requireVector(String slot) {\n        VectorValue value = vectors.get(slot);\n        if (value == null) throw new IllegalArgumentException("Vct" + slot + " 未定义");\n        return value;\n    }',
     '    private MatrixValue requireMatrix(String slot) {\n        MatrixValue value = "Ans".equals(slot) ? matrixAns : matrices.get(slot);\n        if (value == null) throw new IllegalArgumentException(\n                "Ans".equals(slot) ? "MatAns 未定义" : "Mat" + slot + " 未定义");\n        return value;\n    }\n\n    private VectorValue requireVector(String slot) {\n        VectorValue value = "Ans".equals(slot) ? vectorAns : vectors.get(slot);\n        if (value == null) throw new IllegalArgumentException(\n                "Ans".equals(slot) ? "VctAns 未定义" : "Vct" + slot + " 未定义");\n        return value;\n    }'),
    ('    private CnCwModeEngine.ModeResult matrixResult(String title, MatrixValue value) {',
     '    private CnCwModeEngine.ModeResult rememberMatrixResult(String title, MatrixValue value) {\n        matrixAns = value;\n        return matrixResult(title, value);\n    }\n\n    private CnCwModeEngine.ModeResult rememberVectorResult(String title, VectorValue value) {\n        vectorAns = value;\n        return vectorResult(title, value);\n    }\n\n    private CnCwModeEngine.ModeResult matrixResult(String title, MatrixValue value) {'),
])

edit('core/src/main/java/com/codex/fx991/core/cw/CnCwMachine.java', [
    ('                {"sum(", "Σ(", "sum("},\n                {"abs(", "Abs(", "abs("},',
     '                {"sum(", "Σ(", "sum("},\n                {"conjugate(", "Conjg(", "conj("},\n                {"conj(", "Conjg(", "conj("},\n                {"real(", "Re(", "re("},\n                {"imag(", "Im(", "im("},\n                {"arg(", "Arg(", "arg("},\n                {"re(", "Re(", "re("},\n                {"im(", "Im(", "im("},\n                {"abs(", "Abs(", "abs("},'),
    ('    private void powerOff() {\n        workflowSession = null;',
     '    private void powerOff() {\n        workflowSession = null;\n        linearAlgebraMemory.clear();'),
    ('        activeCommandId = command.id();\n        CnCwWorkflowSpec.WorkflowSpec workflowSpec =',
     '        activeCommandId = command.id();\n        if ((application == ApplicationMode.MATRIX && command.id().equals("matrix-ans"))\n                || (application == ApplicationMode.VECTOR && command.id().equals("vector-ans"))) {\n            try {\n                CnCwModeEngine.ModeResult modeResult = linearAlgebraMemory.answer(application);\n                applicationResult = modeResult;\n                double scalar = modeResult.primaryValue() == null\n                        ? (hasAns ? ans : 0.0) : modeResult.primaryValue();\n                commitSuccessfulResult(modeResult.display(), scalar, null, "", true, false);\n            } catch (IllegalArgumentException error) {\n                commitCalculationError(CalculationError.ARGUMENT, 0);\n            }\n            return;\n        }\n        CnCwWorkflowSpec.WorkflowSpec workflowSpec ='),
    ('            case CATALOG -> {\n                openPopup(switch (index) {',
     '            case CATALOG -> {\n                if (application == ApplicationMode.COMPLEX && index == 9) {\n                    openPopup(CnCwScreen.CATALOG_COMPLEX);\n                    break;\n                }\n                openPopup(switch (index) {'),
    ('            case CATALOG_PROBABILITY -> insertFromMenu(probabilityToken(index));\n            case CATALOG_RELATIONS -> insertFromMenu(relationToken(index));',
     '            case CATALOG_PROBABILITY -> insertFromMenu(probabilityToken(index));\n            case CATALOG_COMPLEX -> insertFromMenu(complexToken(index));\n            case CATALOG_RELATIONS -> insertFromMenu(relationToken(index));'),
    ('        spreadsheet.clearAll();\n        tokens.clear();',
     '        spreadsheet.clearAll();\n        linearAlgebraMemory.clear();\n        tokens.clear();'),
    ('    private Token probabilityToken(int index) {',
     '    private Token complexToken(int index) {\n        return switch (index) {\n            case 0 -> token("Conjg(", "conj(");\n            case 1 -> token("Arg(", "arg(");\n            case 2 -> token("Re(", "re(");\n            default -> token("Im(", "im(");\n        };\n    }\n\n    private Token probabilityToken(int index) {'),
    ('            case CATALOG -> com.codex.fx991.core.Compat.list(\n                    command("analysis", "函数与分析", "导数、积分、求和、对数"),\n                    command("probability", "概率", "%、阶乘、排列组合、随机数"),\n                    command("numeric", "数值计算", "绝对值与四舍五入"),\n                    command("angle", "角度/坐标/六十进制", "角度单位、Pol、Rec、DMS"),\n                    command("trig", "双曲/反双曲/三角", "12 个函数"),\n                    command("engineering", "工程符号", "m、μ、n、p、f、k…"),\n                    command("constants", "科学常数", "47 个 CODATA 2018 常数"),\n                    command("conversion", "单位换算", "40 个换算命令"),\n                    command("other", "其他", "关系、多语句与存储"));',
     '            case CATALOG -> catalogRootCommands();'),
    ('            case CATALOG_PROBABILITY -> com.codex.fx991.core.Compat.list(\n                    command("percent", "%", "百分数"), command("factorial", "!", "阶乘"),',
     '            case CATALOG_COMPLEX -> com.codex.fx991.core.Compat.list(\n                    command("conj", "Conjg(", "共轭复数"),\n                    command("arg", "Arg(", "辐角"),\n                    command("re", "Re(", "实部"),\n                    command("im", "Im(", "虚部"));\n            case CATALOG_PROBABILITY -> com.codex.fx991.core.Compat.list(\n                    command("percent", "%", "百分数"), command("factorial", "!", "阶乘"),'),
    ('    private static List<CnCwCommand> engineeringCommands() {',
     '    private List<CnCwCommand> catalogRootCommands() {\n        List<CnCwCommand> items = new ArrayList<>(com.codex.fx991.core.Compat.list(\n                command("analysis", "函数与分析", "导数、积分、求和、对数"),\n                command("probability", "概率", "%、阶乘、排列组合、随机数"),\n                command("numeric", "数值计算", "绝对值与四舍五入"),\n                command("angle", "角度/坐标/六十进制", "角度单位、Pol、Rec、DMS"),\n                command("trig", "双曲/反双曲/三角", "12 个函数"),\n                command("engineering", "工程符号", "m、μ、n、p、f、k…"),\n                command("constants", "科学常数", "47 个 CODATA 2018 常数"),\n                command("conversion", "单位换算", "40 个换算命令"),\n                command("other", "其他", "关系、多语句与存储")));\n        if (application == ApplicationMode.COMPLEX) {\n            items.add(command("complex", "复数", "Conjg、Arg、Re、Im"));\n        }\n        return com.codex.fx991.core.Compat.copyList(items);\n    }\n\n    private static List<CnCwCommand> engineeringCommands() {'),
    ('                    command("matrix-multiply", "矩阵乘法", "Mat×Mat"));',
     '                    command("matrix-multiply", "矩阵乘法", "Mat×Mat"),\n                    command("matrix-square", "矩阵平方", "Mat²"),\n                    command("matrix-cube", "矩阵立方", "Mat³"),\n                    command("matrix-identity", "单位矩阵", "Identity(n)"),\n                    command("matrix-abs", "元素绝对值", "Abs(Mat)"),\n                    command("matrix-ans", "MatAns", "矩阵答案存储器"));'),
    ('                    command("vector-cross", "叉积", "Vct×Vct"),\n                    command("vector-angle", "夹角", "Angle(Vct,Vct)"));',
     '                    command("vector-cross", "叉积", "Vct×Vct"),\n                    command("vector-angle", "夹角", "Angle(Vct,Vct)"),\n                    command("vector-ans", "VctAns", "向量答案存储器"));'),
    ('            case CATALOG_CONVERSION_ITEMS -> "单位换算";\n            case CATALOG_PROBABILITY -> "概率";',
     '            case CATALOG_CONVERSION_ITEMS -> "单位换算";\n            case CATALOG_PROBABILITY -> "概率";\n            case CATALOG_COMPLEX -> "复数";'),
])

# Extend functionality regression with old-manual matrix/vector commands.
edit('core/src/regression/java/com/codex/fx991/core/CnCwFunctionalitySuite.java', [
    ('        openBinaryChoiceCommand(machine, 7, 10); // MatA * MatB\n        equal("1", machine.state().applicationResult().cells().get(0), "matrix multiply identity");\n        equal("4", machine.state().applicationResult().cells().get(3), "matrix multiply identity last");',
     '        openBinaryChoiceCommand(machine, 7, 10); // MatA * MatB\n        equal("1", machine.state().applicationResult().cells().get(0), "matrix multiply identity");\n        equal("4", machine.state().applicationResult().cells().get(3), "matrix multiply identity last");\n\n        openCommand(machine, 7, 11); // MatA^2\n        machine.dispatch(CnCwKey.EXE);\n        equal("7", machine.state().applicationResult().cells().get(0), "matrix square [1,1]");\n        equal("22", machine.state().applicationResult().cells().get(3), "matrix square [2,2]");\n\n        openCommand(machine, 7, 12); // MatA^3\n        machine.dispatch(CnCwKey.EXE);\n        equal("37", machine.state().applicationResult().cells().get(0), "matrix cube [1,1]");\n        equal("118", machine.state().applicationResult().cells().get(3), "matrix cube [2,2]");\n\n        openCommand(machine, 7, 13); // Identity(3)\n        enter(machine, "3");\n        machine.dispatch(CnCwKey.EXE);\n        equal(3, machine.state().applicationResult().rows(), "identity matrix rows");\n        equal(3, machine.state().applicationResult().columns(), "identity matrix columns");\n        equal("1", machine.state().applicationResult().cells().get(0), "identity diagonal");\n        equal("0", machine.state().applicationResult().cells().get(1), "identity off diagonal");\n\n        openCommand(machine, 7, 14); // Abs(MatA)\n        machine.dispatch(CnCwKey.EXE);\n        equal("3", machine.state().applicationResult().cells().get(2), "matrix element abs");\n\n        openCommand(machine, 7, 15); // MatAns\n        equal("Abs(MatA)", machine.state().applicationResult().title(),\n                "MatAns preserves last matrix result payload");'),
    ('        openBinaryChoiceCommand(machine, 8, 11); // angle\n        check(parse(machine, 0) > 36.0 && parse(machine, 0) < 37.0,\n                "VctA/VctB angle is about 36.87 degrees");',
     '        openBinaryChoiceCommand(machine, 8, 11); // angle\n        check(parse(machine, 0) > 36.0 && parse(machine, 0) < 37.0,\n                "VctA/VctB angle is about 36.87 degrees");\n\n        openBinaryChoiceCommand(machine, 8, 7); // A+B -> VctAns\n        openCommand(machine, 8, 12); // VctAns\n        equal("VctA+VctB", machine.state().applicationResult().title(),\n                "VctAns preserves last vector result payload");\n        equal("3", machine.state().applicationResult().cells().get(0), "VctAns x");\n        equal("5", machine.state().applicationResult().cells().get(1), "VctAns y");'),
])

# Add complex dedicated catalog coverage and reset/power-off memory assertions.
edit('core/src/regression/java/com/codex/fx991/core/CnCwCompletenessSuite.java', [
    ('        complexApplicationRunsRectangularAndPolarPaths();\n        constantCatalogExposesEveryRegistryEntry();',
     '        complexApplicationRunsRectangularAndPolarPaths();\n        complexDedicatedCommandsAreReachable();\n        constantCatalogExposesEveryRegistryEntry();'),
    ('    private void constantCatalogExposesEveryRegistryEntry() {',
     '    private void complexDedicatedCommandsAreReachable() {\n        CnCwMachine machine = openApplication(5);\n        machine.dispatch(CnCwKey.CATALOG);\n        moveDown(machine, 9);\n        machine.dispatch(CnCwKey.OK);\n        equal(com.codex.fx991.core.cw.CnCwScreen.CATALOG_COMPLEX, machine.state().screen(),\n                "Complex catalog opens dedicated command group");\n        equal(4, machine.state().menuItems().size(), "Complex catalog command count");\n        machine.dispatch(CnCwKey.OK); // Conjg(\n        press(machine, CnCwKey.DIGIT_2, CnCwKey.ADD, CnCwKey.DIGIT_3,\n                CnCwKey.SHIFT, CnCwKey.DIGIT_9, CnCwKey.EXE);\n        equal("2−3i", machine.state().result(), "Conjg command runs through user catalog");\n\n        machine = openApplication(5);\n        machine.dispatch(CnCwKey.CATALOG); moveDown(machine, 9); machine.dispatch(CnCwKey.OK);\n        machine.dispatch(CnCwKey.DOWN); machine.dispatch(CnCwKey.OK); // Arg(\n        press(machine, CnCwKey.DIGIT_1, CnCwKey.ADD, CnCwKey.SHIFT, CnCwKey.DIGIT_9,\n                CnCwKey.EXE);\n        near(45.0, machine.state().ans(), 1e-10, "Arg command");\n\n        machine = openApplication(5);\n        machine.dispatch(CnCwKey.CATALOG); moveDown(machine, 9); machine.dispatch(CnCwKey.OK);\n        moveDown(machine, 2); machine.dispatch(CnCwKey.OK); // Re(\n        press(machine, CnCwKey.DIGIT_2, CnCwKey.ADD, CnCwKey.DIGIT_3,\n                CnCwKey.SHIFT, CnCwKey.DIGIT_9, CnCwKey.EXE);\n        near(2.0, machine.state().ans(), 1e-12, "Re command");\n\n        machine = openApplication(5);\n        machine.dispatch(CnCwKey.CATALOG); moveDown(machine, 9); machine.dispatch(CnCwKey.OK);\n        moveDown(machine, 3); machine.dispatch(CnCwKey.OK); // Im(\n        press(machine, CnCwKey.DIGIT_2, CnCwKey.ADD, CnCwKey.DIGIT_3,\n                CnCwKey.SHIFT, CnCwKey.DIGIT_9, CnCwKey.EXE);\n        near(3.0, machine.state().ans(), 1e-12, "Im command");\n    }\n\n    private void constantCatalogExposesEveryRegistryEntry() {'),
])
