from pathlib import Path

path = Path('app/src/main/java/com/codex/fx991smooth/CalculatorView.java')
text = path.read_text(encoding='utf-8')

old = '''                        float handleTop = contentTop + dp(1.5f) - dp(2.2f);\n                        float handleBottom = Math.min(contentBottom - dp(10),\n                                contentTop + dp(34)) + dp(2.2f);\n                        float startX = displayBoundaryX(state.selectionStart());\n                        float endX = displayBoundaryX(state.selectionEnd());\n                        float startDistance = (float) Math.hypot(\n                                event.getX() - startX, event.getY() - handleBottom);\n                        float endDistance = (float) Math.hypot(\n                                event.getX() - endX, event.getY() - handleTop);\n                        float handleSlop = dp(15);\n                        if (Math.min(startDistance, endDistance) <= handleSlop) {\n                            selectionDragEdge = startDistance <= endDistance ? -1 : 1;\n                            displaySelectionMode = true;\n                            lastDragCursor = selectionDragEdge < 0\n                                    ? state.selectionStart() : state.selectionEnd();\n                            performHapticFeedback(HapticFeedbackConstants.CLOCK_TICK);\n                            return true;\n                        }\n'''
new = '''                        float startX = displayBoundaryX(state.selectionStart());\n                        float endX = displayBoundaryX(state.selectionEnd());\n                        // Keep the handles visually small, but give each boundary a much\n                        // larger phone-style grab zone. Users should not need to land on\n                        // the tiny knob itself before they can adjust an existing selection.\n                        float handleHitTop = contentTop - dp(10);\n                        float handleHitBottom = Math.min(contentBottom, contentTop + dp(52));\n                        float handleXSlop = dp(26);\n                        boolean inHandleBand = event.getY() >= handleHitTop\n                                && event.getY() <= handleHitBottom;\n                        float startXDistance = Math.abs(event.getX() - startX);\n                        float endXDistance = Math.abs(event.getX() - endX);\n                        boolean startHit = inHandleBand && startXDistance <= handleXSlop;\n                        boolean endHit = inHandleBand && endXDistance <= handleXSlop;\n                        if (startHit || endHit) {\n                            selectionDragEdge = startHit && endHit\n                                    ? (startXDistance <= endXDistance ? -1 : 1)\n                                    : startHit ? -1 : 1;\n                            displaySelectionMode = true;\n                            lastDragCursor = selectionDragEdge < 0\n                                    ? state.selectionStart() : state.selectionEnd();\n                            performHapticFeedback(HapticFeedbackConstants.CLOCK_TICK);\n                            return true;\n                        }\n'''
if old not in text:
    raise SystemExit('selection handle block not found')
text = text.replace(old, new, 1)

old = '''                    displayLongPress = () -> {\n                        if (displayPressed) {\n                            performHapticFeedback(HapticFeedbackConstants.LONG_PRESS);\n                            displayLongPressTriggered = true;\n                            int anchor = displayCursorPosition(displayDownX);\n                            state = machine.selectTouchWord(anchor);\n                            lastDragCursor = state.cursor();\n                            selectionDragEdge = 0;\n                            displaySelectionMode = true;\n                            postInvalidateOnAnimation();\n                        }\n                    };\n'''
new = '''                    displayLongPress = () -> {\n                        if (displayPressed) {\n                            performHapticFeedback(HapticFeedbackConstants.LONG_PRESS);\n                            displayLongPressTriggered = true;\n                            if (machine.cursorLimit() == 0) {\n                                // There is nothing to select on an empty editor. Long-press\n                                // should still expose the standard phone action the user\n                                // needs here: paste from the system clipboard.\n                                displaySelectionMode = false;\n                                selectionDragEdge = 0;\n                                postInvalidateOnAnimation();\n                                showPasteOnlyMenu();\n                                return;\n                            }\n                            int anchor = displayCursorPosition(displayDownX);\n                            state = machine.selectTouchWord(anchor);\n                            lastDragCursor = state.cursor();\n                            selectionDragEdge = 0;\n                            displaySelectionMode = true;\n                            postInvalidateOnAnimation();\n                        }\n                    };\n'''
if old not in text:
    raise SystemExit('display long press block not found')
text = text.replace(old, new, 1)

needle = '''    private void showClipboardMenu() {\n'''
insert = '''    private void showPasteOnlyMenu() {\n        new AlertDialog.Builder(getContext()).setItems(new String[]{"粘贴"}, (dialog, which) -> {\n            performHapticFeedback(HapticFeedbackConstants.KEYBOARD_TAP);\n            pasteClipboardText();\n        }).show();\n    }\n\n'''
if needle not in text:
    raise SystemExit('clipboard menu method not found')
text = text.replace(needle, insert + needle, 1)

path.write_text(text, encoding='utf-8')
print('patched selection handle hit area and empty-editor long press paste')
